### ISSUE TITLE
config.json file not generated after training

### ISSUE THREAD

**Issue by TitasDas** [BUTSpeechFIT/BaySMM#1]
Came across BaySMM and was trying to do topic modelling on a custom dataset - that primarily is a csv file consisting of two columns :

1. Publishing date
2. Headlines of the article

As far as I understood the instructions. I used the first command to generate the right sampling from this csv (doesn't have labels) and then went onto executing the training of the model. 

The error I am coming across is as follows : 

1. The first one is a file not found error - 

`_**FileNotFoundError: [Errno 2] No such file or directory: '/Users/t***/Desktop/topic-modelling/BaySMM-master/exp/s_1.00_rp_1_lw_1e+01_l1_1e-03_50_adam/config.json'**_`

because of which the follow up error occurs 
2. 

`_**AttributeError: 'Namespace' object has no attribute 'update_ubm'**_`

where essentially the args are not being parsed. 

Is there a certain way the data must be sampled for creating the config.json? Why is the config.json file not being created post training? @skesiraju

**Comment by skesiraju** [comment]
Hi @TitasDas 
Thanks for the report. The error was due to `args.update_ubm` which was an obsolete option. Now it is commented out, and the code should work fine.
https://github.com/BUTSpeechFIT/BaySMM/blob/d961baf028245c62f1ee9a94925630da42a3c7b8/src/utils.py#L444

**Comment by TitasDas** [comment]
I confirm that this is fixed. Thank you for your response and fixing this. However, this further stops at another error about which I am posting another issue.
