### ISSUE TITLE
test model file not found

### ISSUE THREAD

**Issue by TitasDas** [BUTSpeechFIT/BaySMM#2]
After running all the commands as per the instructions. When I finally run - 

`python src/train_and_clf_cv.py exp/s_1.00_rp_1_lw_1e+01_l1_1e-03_50_adam/ivecs/train_model_T1000_e1000.h5 sample_data/train.labels glc
`
I get the following error stating that the corresponding test model file is not present. (I ran the training for 100 iterations instead of 1000.)

> .\exp\s_1.00_rp_1_lw_1e+01_l1_1e-03_50_adam\ivecs\test_model_T100_e1000.h5 not found.

Also went through most of the code, not sure how to go about producing a test model. Would appreciate it if you pointed me in the right direction. @skesiraju

**Comment by skesiraju** [comment]
Did you extract the i-vectors (embeddings) for both training and test data, using the trained model (in your case `model_T100.h5`)?
[See the second step: Extracting the posterior distributions of embeddings
](https://github.com/BUTSpeechFIT/BaySMM#extracting-the-posterior-distributions-of-embeddings)

If yes, there should be the following two files created under the direcotry `.\exp\s_1.00_rp_1_lw_1e+01_l1_1e-03_50_adam\ivecs\`
- `train_modelT100_exxxx.h5`
- `test_modelT100_exxxx.h5`

Also the following lines have changed 
https://github.com/BUTSpeechFIT/BaySMM/blob/5f1dba4426a1ef121c90a0bfbd2f2147bb498c62/src/train_and_clf_cv.py#L70-L72

**Comment by TitasDas** [comment]
Thank you, upon rechecking what was happening is due to an error regarding **_'rm -rf'_** commands the program was exiting and the test file was not being generated. Just commented those lines from **utils.py** out since they didn't have any particular functionality in terms of the algorithm in use and it works just fine. 

Have a couple of questions more regarding using it on a custom dataset and viewing the identified topics etc.
