### ISSUE TITLE
Interpreting the results

### ISSUE THREAD

**Issue by TitasDas** [BUTSpeechFIT/BaySMM#4]
I ran the commands and was able to generate the results and numbers as expected. Now I would like to know if we can see which  topics were identified from the text etc. Would this be possible here? (If you find this question to be ambiguous I can add in more details. Basically along with the numbers I am also looking for the actual topics that are picked up from my dataset.)

**Comment by skesiraju** [comment]
Apologies for very long delay in response. Please see the example [here for automatic topic discovery](https://github.com/BUTSpeechFIT/BaySMM#topic-discovery)
